<a href="https://colab.research.google.com/github/Fahadqureshi0/Handling-Imbalanced-Dataset/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Handling Imbalanced Dataset**
A Dataset with an unequal class Distribution

In [1]:
# Importing the Dependencies
import numpy as np
import pandas as pd

In [2]:
# Loading the Dataset into Pandas Dataframe
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [4]:
# First 5 rows of the DataFrame
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
# Distribution of the two classes
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is highly Imbalanced Datset

0 --> Transactions are Legit
1 --> Transactions are Fraudulent

In [11]:
# Seprating the Fraudlent and Legit Transaction
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [12]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

Applying the Undersampling to handle Imbalanced Data

**Building a sample dataset containing the similar distribution of legit and Fraudlent Transaction**

Number of Fraudlent Transaction -> 492

In [13]:
legit_sample = legit.sample(n=492)

In [14]:
print(legit_sample.shape)

(492, 31)

**Concatenate the two DataFrames**

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [17]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
47333,43175.0,-2.828585,1.898277,0.773683,0.216591,-1.233219,-0.836792,-0.174347,0.754873,0.114933,...,-0.058369,-0.407470,0.004100,0.720493,0.342155,0.184949,-1.329666,-0.279010,19.22,0
239280,150032.0,-1.311303,-0.409165,2.998430,-1.063874,-1.739016,0.664132,-1.022779,0.540535,1.045071,...,-0.384062,-0.112685,-0.313640,0.050991,0.358882,0.877063,0.287470,0.252820,40.00,0
88696,62250.0,1.103270,-1.158017,1.230129,-0.445480,-1.960996,-0.448128,-1.127234,0.015157,-0.206805,...,-0.094648,-0.026546,-0.025437,0.440561,-0.086126,1.102496,-0.024423,0.047748,125.90,0
240929,150812.0,2.251747,-1.370419,-0.830451,-1.557172,-1.360101,-0.755494,-1.128986,-0.124103,-1.441630,...,-0.113170,0.168594,0.243637,-0.009892,-0.236161,-0.178588,0.006765,-0.062912,10.00,0
61589,49902.0,1.048408,-1.110872,0.089010,-0.577738,-0.999027,-0.382442,-0.356838,-0.082108,-0.859026,...,0.143971,0.004605,-0.232923,0.042209,0.485413,-0.269267,-0.031698,0.029782,184.65,0

In [18]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [19]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64